[package]
name = "tweakable-modbus"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
async-trait = "0.1.88"
byteorder = "1.5.0"
num_enum = "0.7.3"
tokio = { version = "1.37", features = ["full"] }
